### ISSUE TITLE
关于ts支持和打包

### ISSUE THREAD

**Issue by lopo12123** [Hector-Chong/native-wechat#16]
我发现您的包并没有做打包处理，而是直接把文件放在了src目录下进行使用。
而且您在文档中描述有ts支持，但是实际使用并没有任何的ts支持（没有.d.ts 也没有在package.json 中指明 types 字段)

希望能添加打包和ts支持, 便于ide的自动提示功能, 谢谢

**Comment by Hector-Chong** [comment]
https://github.com/Hector-Chong/native-wechat/pull/18
