### ISSUE TITLE
Error when registering app

### ISSUE THREAD

**Issue by inmess** [Hector-Chong/native-wechat#22]
Somehow I can not register the app properly.
Here are the codes. (appid and universalLink is correct)
```
        // below applied in useEffect of App.js
        try {
            registerApp({
                appid: 'wx******14',
                universalLink: 'https://my.domain.com/*/',
                log: true
            })  
            checkUniversalLinkReady()
                .then(console.log)
                .catch(e => console.log(e))
        } catch (error) {
            console.log(error);
        }
```
Errors:
```
{
    "errorInfo": "appId or universalLink is nil", 
    "suggestion": "Please pass the correct parameters when calling the +[WXApi register:universalLink:] function"
}
```
My rewritten ios native code can refer the issue #21 I opened couple of days ago.

I'm a little confused right now, cuz I've got approved on Wechat, I've alse tested universal link and working properly now.

Is that I misunderstood the doc and implemented it in a wrong way? @Hector-Chong

**Comment by inmess** [comment]
NVM, Just add following to `ios/PROJECT/info.plist` solved my problem for now.
![image](https://user-images.githubusercontent.com/48652450/220562189-b418f39e-e48f-4cd3-b970-b676acba7bb5.png)

**Comment by Hector-Chong** [comment]
Though it's not my problem, I would add this to the docs...
