### ISSUE TITLE
Class 'AppDelegate' does not conform to protocol 'RCTBridgeDelegate'

### ISSUE THREAD

**Issue by Latrixz** [Hector-Chong/native-wechat#23]
i have the issue when following the guide, how do i solve the problem above?

![image](https://user-images.githubusercontent.com/55631050/223703299-865a0e89-b6ee-4e00-b93c-12567fb49a6d.png)

**Comment by Latrixz** [comment]
it's the same as what u posted, let me take a screenshot
![image](https://user-images.githubusercontent.com/55631050/223913266-86a14cff-6a55-4a3e-9261-b940920ce08d.png)

**Comment by Hector-Chong** [comment]
According to the docs, there are three delegates. You missed one.

```
@interface AppDelegate : EXAppDelegateWrapper <UIApplicationDelegate, RCTBridgeDelegate, WXApiDelegate>
```
