### ISSUE TITLE
react native to WeChat miniprogram

### ISSUE THREAD

**Issue by bylzlhs** [Hector-Chong/native-wechat#24]
Hello, I saw this project called "native WeChat" and I understand it to be a tool that can convert programs built with the React Native framework into WeChat Mini Programs. I'm not sure if my understanding is correct.

Currently, I have a core business functionality developed using React Native, and I would like to convert it into WeChat Mini Program code and publish it on the Mini Program platform. Additionally, after using this tool to convert the code, I would still need to incorporate basic functionalities such as sharing, payment, user authentication, and user information retrieval using the existing WeChat APIs. Will this be affected?

I'm not very familiar with technical development, and I'm not proficient in using GitHub. I'm unsure where to ask these questions, so I apologize if I have posted in the wrong place. Thank you very much!

**Comment by Hector-Chong** [comment]
Actually, this library does not covert code for you. This library helps you call Wechat API using JavaScript.

However, if you want to develop Wechat Mini Program using React, [Taro](https://taro-docs.jd.com/) is the best choice.

I'm sorry for my naming issue that confuses you.
