### ISSUE TITLE
您好，安卓这边有个warning呢

### ISSUE THREAD

**Issue by bobacCurry** [Hector-Chong/native-wechat#25]
WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.

还有我发现您的参数格式已经变了，但是文档没有更新。

**Comment by hdjhdjhdj** [comment]
大佬，后面怎么解决了

**Comment by bobacCurry** [comment]
> 大佬，后面怎么解决了

好像是换了个插件

**Comment by Hector-Chong** [comment]
https://github.com/Hector-Chong/native-wechat/commit/1fa3c46fae88e2e730462a102eb50a6c0e02ee98

**Comment by hdjhdjhdj** [comment]
@Hector-Chong 
v1.0.17还是有这个warning
不是修复的 fix: 🐛 NativeEventEmitter warning
还少了removeListeners

**Comment by hdjhdjhdj** [comment]
修复警告
参考 https://stackoverflow.com/questions/69538962/new-nativeeventemitter-was-called-with-a-non-null-argument-without-the-requir
![image](https://github.com/user-attachments/assets/65feaaf9-afb6-4dfa-a8a4-19b72e338381)
