### ISSUE TITLE
Unknown type name 'WXOpenCustomerServiceReq'

### ISSUE THREAD

**Issue by DingTianYi9** [Hector-Chong/native-wechat#26]
按照您Web上的配置进行了修改 IOS端报错
<img width="1210" alt="image" src="https://github.com/Hector-Chong/native-wechat/assets/50064250/d348adbb-be25-4065-85ac-78c3b804a347">

这是我的.mm和.h文件 因为对IOS原声不熟悉 不知道是不是自己哪里配置错了
项目是React-Native 0.71.6
![image](https://github.com/Hector-Chong/native-wechat/assets/50064250/5783d64c-24bd-49cd-8857-eca0eace32c5)
![image](https://github.com/Hector-Chong/native-wechat/assets/50064250/e978a527-e9b2-478f-9184-e8039b8e24bd)
![image](https://github.com/Hector-Chong/native-wechat/assets/50064250/316b5c4d-163b-4dda-9cd3-41c5fb470023)
![image](https://github.com/Hector-Chong/native-wechat/assets/50064250/654bb49f-28cd-4ad2-a675-e956e116102c)
![image](https://github.com/Hector-Chong/native-wechat/assets/50064250/8f12c1e2-3a19-44b8-99d4-bb69505da41c)
期待您的回复

**Comment by Hector-Chong** [comment]
It seems that the header file related to WeChat Open SDK is missing.

Ensure you've executed `pod install` in your project's `ios` folder.

看起来似乎微信 OpenSDK 的头文件没有集成到您的项目。

请确保您在项目的 `ios` 目录执行了 `pod install` 命令。

**Comment by DingTianYi9** [comment]
> 想要缺微信打开SDK相关的头文件。
> 
> `pod install`确保您已在项目文件夹中执行`ios`。
> 
> 看起来微信 OpenSDK 的头文件没有集成到您的项目。
> 
> 请确保您在项目的`ios`目录执行了`pod install`命令。

这是我的AppDelegate.mm配置
#import "AppDelegate.h"

#import <React/RCTBundleURLProvider.h>

#if RCT_NEW_ARCH_ENABLED
#import <React/CoreModulesPlugins.h>
#import <React/RCTCxxBridgeDelegate.h>
#import <React/RCTFabricSurfaceHostingProxyRootView.h>
#import <React/RCTSurfacePresenter.h>
#import <React/RCTSurfacePresenterBridgeAdapter.h>
#import <ReactCommon/RCTTurboModuleManager.h>

#import <react/config/ReactNativeConfig.h>

static NSString *const kRNConcurrentRoot = @"concurrentRoot";

@interface AppDelegate () <RCTCxxBridgeDelegate, RCTTurboModuleManagerDelegate> {
  RCTTurboModuleManager *_turboModuleManager;
  RCTSurfacePresenterBridgeAdapter *_bridgeAdapter;
  std::shared_ptr<const facebook::react::ReactNativeConfig> _reactNativeConfig;
  facebook::react::ContextContainer::Shared _contextContainer;
}
@end
#endif


@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  RCTAppSetupPrepareApp(application);

  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];

  #if RCT_NEW_ARCH_ENABLED
    _contextContainer = std::make_shared<facebook::react::ContextContainer const>();
    _reactNativeConfig = std::make_shared<facebook::react::EmptyReactNativeConfig const>();
    _contextContainer->insert("ReactNativeConfig", _reactNativeConfig);
    _bridgeAdapter = [[RCTSurfacePresenterBridgeAdapter alloc] initWithBridge:bridge contextContainer:_contextContainer];
    bridge.surfacePresenter = _bridgeAdapter.surfacePresenter;
  #endif

  self.moduleName = @"RNSanJiangApp";
  self.initialProps = @{};

  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}

#if RCT_NEW_ARCH_ENABLED

#pragma mark - RCTCxxBridgeDelegate

- (std::unique_ptr<facebook::react::JSExecutorFactory>)jsExecutorFactoryForBridge:(RCTBridge *)bridge
{
  _turboModuleManager = [[RCTTurboModuleManager alloc] initWithBridge:bridge
                                                             delegate:self
                                                            jsInvoker:bridge.jsCallInvoker];
  return RCTAppSetupDefaultJsExecutorFactory(bridge, _turboModuleManager);
}

#pragma mark RCTTurboModuleManagerDelegate

- (Class)getModuleClassFromName:(const char *)name
{
  return RCTCoreModulesClassProvider(name);
}

- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:(const std::string &)name
                                                      jsInvoker:(std::shared_ptr<facebook::react::CallInvoker>)jsInvoker
{
  return nullptr;
}

- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:(const std::string &)name
                                                     initParams:
                                                         (const facebook::react::ObjCTurboModule::InitParams &)params
{
  return nullptr;
}

- (id<RCTTurboModule>)getModuleInstanceFromClass:(Class)moduleClass
{
  return RCTAppSetupDefaultModuleFromClass(moduleClass);
}

#endif


- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index"];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

- (BOOL)concurrentRootEnabled
{
  return true;
}

- (BOOL)application:(UIApplication *)application
   openURL:(NSURL *)url
   options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  [WXApi handleOpenURL:url delegate:self];
  
  return [RCTLinkingManager application:application openURL:url options:options];
}

- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url
  sourceApplication:(NSString *)sourceApplication annotation:(id)annotation
{
  return [WXApi handleOpenURL:url delegate:self];
}

- (BOOL)application:(UIApplication *)application continueUserActivity:(nonnull NSUserActivity *)userActivity
 restorationHandler:(nonnull void (^)(NSArray<id<UIUserActivityRestoring>> * _Nullable))restorationHandler
{
  [RCTLinkingManager application:application
                  continueUserActivity:userActivity
                    restorationHandler:restorationHandler];
  
  return [WXApi handleOpenUniversalLink:userActivity delegate:self];
}

@end

**Comment by DingTianYi9** [comment]
> > 想要缺微信的打开SDK相关的头文件。
> > `pod install`确保您已在项目文件夹中执行`ios`。
> > 看起来微信 OpenSDK 的头文件没有集成到您的项目。
> > 请确保您在项目的`ios`目录执行了`pod install`命令。
> 
> 这是我的AppDelegate.mm配置 #import "AppDelegate.h"
> 
> #import <React/RCTBundleURLProvider.h>
> 
> #if RCT_NEW_ARCH_ENABLED #import <React/CoreModulesPlugins.h> #import <React/RCTCxxBridgeDelegate.h> #import <React/RCTFabricSurfaceHostingProxyRootView.h> #import <React /RCTSurfacePresenter.h> #import <React/RCTSurfacePresenterBridgeAdapter.h> #import <ReactCommon/RCTTurboModuleManager.h >
> 
> #import <react/config/ReactNativeConfig.h>
> 
> 静态 NSString *const kRNConcurrentRoot = @"concurrentRoot";
> 
> @interfaceAppDelegate () <RCTCxxBridgeDelegate, RCTTurboModuleManagerDelegate> { RCTTurboModuleManager *_turboModuleManager; RCTurfacePresenterBridgeAdapter *_bridgeAdapter; std::shared_ptr _reactNativeConfig; facebook::react::ContextContainer::Shared _contextContainer； } @EnD ＃万一
> 
> @implementation应用程序代理
> 
> * (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions 
>   { 
>   RCTAppSetupPrepareApp(application);
>   RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
>   #if RCT_NEW_ARCH_ENABLED 
>   _contextContainer = std::make_shared<facebook::react::ContextContainer const>(); 
>   _reactNativeConfig = std::make_shared<facebook::react::EmptyReactNativeConfig const>(); 
>   _contextContainer->insert("ReactNativeConfig", _reactNativeConfig); 
>   _bridgeAdapter = [[RCTSurfacePresenterBridgeAdapter alloc] initWithBridge:bridge contextContainer:_contextContainer]; 
>   桥接器.surfacePresenter = _bridgeAdapter.surfacePresenter; 
>   ＃万一
>   self.moduleName = @"RNSanJiangApp"; 
>   self.initialProps = @{};
>   返回[超级应用程序：应用程序didFinishLaunchingWithOptions：launchOptions]；
>   }
> 
> #if RCT_NEW_ARCH_ENABLED
> 
> #pragma mark - RCTCxxBridgeDelegate
> 
> * (std::unique_ptrfacebook::react::JSExecutorFactory)jsExecutorFactoryForBridge:(RCTBridge *)bridge 
>   { 
>   _turboModuleManager = [[RCTTurboModuleManager alloc] initWithBridge:bridge 
>   delegate:self 
>   jsInvoker:bridge.jsCallInvoker]; 
>   返回 RCTAppSetupDefaultJsExecutorFactory(bridge, _turboModuleManager); 
>   }
> 
> #pragma mark RCTTurboModuleManagerDelegate
> 
> * (Class)getModuleClassFromName:(const char *)name 
>   { 
>   return RCTCoreModulesClassProvider(name); 
>   }
> * (std::shared_ptrfacebook::react::TurboModule)getTurboModule:(const std::string &)name 
>   jsInvoker:(std::shared_ptrfacebook::react::CallInvoker)jsInvoker 
>   { 
>   return nullptr; } 
>   }
> * (std::shared_ptrfacebook::react::TurboModule)getTurboModule:(const std::string &)name 
>   initParams: 
>   (const facebook::react::ObjCTurboModule::InitParams &)params 
>   { 
>   return nullptr; 
>   }
> * (id)getModuleInstanceFromClass:(Class)moduleClass 
>   { 
>   return RCTAppSetupDefaultModuleFromClass(moduleClass); 
>   }
> 
> ＃万一
> 
> * (NSURL *)sourceURLForBridge:(RCTBridge *)bridge 
>   { 
>   #if DEBUG 
>   return [[RCTBundleURLProvider shareSettings] jsBundleURLForBundleRoot:@"index"]; 
>   #else 
>   return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"]; 
>   #endif 
>   }
> * (BOOL)concurrentRootEnabled 
>   {
>   返回 true; 
>   }
> * (BOOL)application:(UIApplication *)application 
>   openURL:(NSURL *)url
>   选项:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options 
>   { 
>   [WXApi handleOpenURL:url delegate:self];
>   返回 [RCTLinkingManager 应用程序:应用程序 openURL:url 选项:选项]; 
>   }
> * (BOOL)application:(UIApplication *)application openURL:(NSURL *)url 
>   sourceApplication:(NSString *)sourceApplication 批注:(id)annotation 
>   { 
>   return [WXApi handleOpenURL:url delegate:self]; 
>   }
> * (BOOL)application:(UIApplication *)application continueUserActivity:(nonnull NSUserActivity *)userActivityrestorationHandler 
>   :(nonnull void (^)(NSArray<id> * _Nullable))restorationHandler 
>   { 
>   [RCTLinkingManager application:application 
>   continueUserActivity:userActivityrestorationHandler 
>   :restorationHandler];
>   返回 [WXApi handleOpenUniversalLink:userActivity delegate:self]; 
>   }
> 
> @EnD

这是我.h文件代码配置
#import <React/RCTBridgeDelegate.h>
#import <UIKit/UIKit.h>
#import "WXApi.h" 

@interface AppDelegate : EXAppDelegateWrapper <UIApplicationDelegate, RCTBridgeDelegate, WXApiDelegate>

@end

能否帮忙看下，万分感激

**Comment by DingTianYi9** [comment]
> It seems that the header file related to WeChat Open SDK is missing.
> 
> Ensure you've executed `pod install` in your project's `ios` folder.
> 
> 看起来似乎微信 OpenSDK 的头文件没有集成到您的项目。
> 
> 请确保您在项目的 `ios` 目录执行了 `pod install` 命令。

你好 我的AppDelegate.h文件 原本是这个样子的 按照文档配置成下面注释的 
![image](https://github.com/Hector-Chong/native-wechat/assets/50064250/963d9a85-c91a-41f8-befe-203b03270b61)
我猜测是这里导致了项目编译失败

**Comment by Hector-Chong** [comment]
Is this a native or Expo project?

请问您这个是原生项目还是 Expo 项目？

**Comment by DingTianYi9** [comment]
> 

是React-Native项目，我用其他的库搞定了，感谢
