### ISSUE TITLE
     await requestPayment(obj)没有返回支付信息

### ISSUE THREAD

**Issue by zhen-zhong** [Hector-Chong/native-wechat#31]
作者你好，requestPayment微信支付条转到微信支付完之后，点击返回app，没有返回支付信息，不论是try还是catch都没有返回结果。请问，这是什么情况，是我哪里配置有问题吗？

**Comment by Hector-Chong** [comment]
请提供出现此问题的所使用的的 React Native 版本、设备系统、与配置代码，以便我更好地排查。

**Comment by zhenzhongplus** [comment]
"react": "18.2.0",
  "react-native": "0.72.7",
   oppoA93   android12
   支付成功后点击微信页面的返回按钮直接就返回app，也没有任何提示，该app已经上线了，所以是线上真实环境支付的。
<img width="1255" alt="image" src="https://github.com/Hector-Chong/native-wechat/assets/96850336/132b5209-296d-4044-a79d-3eead04c2fae">
<img width="1347" alt="image" src="https://github.com/Hector-Chong/native-wechat/assets/96850336/9e62e6f0-a594-4307-a8ca-975dc8d21278">
<img width="1278" alt="image" src="https://github.com/Hector-Chong/native-wechat/assets/96850336/4b435109-228c-408b-a9f0-a9ecca75ab7a">
<img width="650" alt="image" src="https://github.com/Hector-Chong/native-wechat/assets/96850336/c23fc7b8-0372-470b-b804-2a358e106212">

**Comment by zhenzhongplus** [comment]
"react": "18.2.0",
"react-native": "0.72.7",
oppoA93 android12
支付成功后点击微信页面的返回按钮直接就返回app，也没有任何提示，该app已经上线了，所以是线上真实环境支付的。
<img width="1052" alt="image" src="https://github.com/Hector-Chong/native-wechat/assets/96850336/bf6d0718-8972-47b7-b990-396ff899cece">
<img width="887" alt="image" src="https://github.com/Hector-Chong/native-wechat/assets/96850336/589b01ac-130c-4a77-8454-bff7958483c4">
<img width="925" alt="image" src="https://github.com/Hector-Chong/native-wechat/assets/96850336/2895ad64-e972-4382-a3a2-737139359a7f">
<img width="612" alt="image" src="https://github.com/Hector-Chong/native-wechat/assets/96850336/8215ec50-db63-4497-b69b-c8ef7bdd67dc">

**Comment by Hector-Chong** [comment]
很抱歉，由于工作调整，我目前没有微信支付相关参数调试此 issue，或你可向我邮箱发送联系方式，我会尽量帮助你解决。

**Comment by zhenzhongplus** [comment]
17638732656这是我的微信，我们可以在微信上讨论这个问题。
---- 回复的原邮件 ----
| 发件人 | Héctor ***@***.***> |
| 发送日期 | 2024年02月02日 10:11 |
| 收件人 | Hector-Chong/native-wechat ***@***.***> |
| 抄送人 | liyang ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [Hector-Chong/native-wechat] await requestPayment(obj)没有返回支付信息 (Issue #31) |

很抱歉，由于工作调整，我目前没有微信支付相关参数调试此 issue，或你可向我邮箱发送联系方式，我会尽量帮助你解决。

**Comment by fullahouse** [comment]
支付的回调与其他回调不同，是传给WXPayEntryActivity这个类的，所以需要在这个类做同样的消息处理操作。希望作者有时间处理一下。感谢作者提供这么棒的库。
<img width="1125" alt="image" src="https://github.com/user-attachments/assets/f0ab458d-d9ed-4416-8f9e-fc105ddbace6">

**Comment by Hector-Chong** [comment]
> 支付的回调与其他回调不同，是传给WXPayEntryActivity这个类的，所以需要在这个类做同样的消息处理操作。希望作者有时间处理一下。感谢作者提供这么棒的库。 <img alt="image" width="1125" src="https://private-user-images.githubusercontent.com/478830/363059269-f0ab458d-d9ed-4416-8f9e-fc105ddbace6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NTkxMjYsIm5iZiI6MTcyNTQ1ODgyNiwicGF0aCI6Ii80Nzg4MzAvMzYzMDU5MjY5LWYwYWI0NThkLWQ5ZWQtNDQxNi04ZjllLWZjMTA1ZGRiYWNlNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNFQxNDA3MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOTQ4Y2RkZGJlZmVlYWUyN2ZmZWMzMWEwOGY0ZDRkOTY3ZDdkMjdjNGNhNGQwODIyMDY1ZDA0NzdmYTkxMWM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.clUFXw9t0Sh0dsEBQ_Sfm-KaWJgnH_6mXMVisTDBFKo">

很抱歉，最近工作比较繁忙，没有来得及查看 GitHub 上的消息。
我知道微信支付回调会调用 App 的 WXPayEntryActivity Activity，文档里有说明 WXPayEntryActivity 需要自己配置。

**Comment by fullahouse** [comment]
文档里的WXPayEntryActivity 只是简单的finish掉了，就像提问者的截图所显示的那样，没有对支付回调的intent做处理，也就导致了reactnative层的requestPayment方法没有返回结果。
我参考WXEntryActivity做了如下修改，就可以正常收到返回结果了。
```
import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;

public class WXPayEntryActivity extends Activity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        try {
          Intent intent = getIntent();
          Intent intentToBroadcast = new Intent();
    
          intentToBroadcast.setAction("com.hector.nativewechat.ACTION_REDIRECT_INTENT");
          intentToBroadcast.putExtra("intent", intent);
    
          sendBroadcast(intentToBroadcast);
    
          finish();
        } catch (Exception e) {
          e.printStackTrace();
        }
    }
}
```

**Comment by Hector-Chong** [comment]
真的很感谢这么晚还在回复消息！这里文档确实有误，我已经更新上去了。不过，库的代码应该没有问题。
