### ISSUE TITLE
缺少了 typesciprt 类型声明

### ISSUE THREAD

**Issue by kunkuntang** [Hector-Chong/native-wechat#36]
![image](https://github.com/Hector-Chong/native-wechat/assets/13299413/d33267f8-0ff4-420b-be26-1dd40a4c74ad)
![image](https://github.com/Hector-Chong/native-wechat/assets/13299413/0a60b7b2-a001-4c22-b7cf-87ad4902fe5c)

![image](https://github.com/Hector-Chong/native-wechat/assets/13299413/9bd51a7e-30b0-4789-bb34-020079c53b3a)

感觉作者忘记放类型进dist目录了

**Comment by Hector-Chong** [comment]
c923f26187aa9680c931ece7c2f3e2551cedce43

**Comment by hdjhdjhdj** [comment]
这个文件在dist里面不存在，找不到类型
![image](https://github.com/user-attachments/assets/1dc53992-7882-4846-adff-eecf6fa5457d)
![image](https://github.com/user-attachments/assets/d126ccfc-618a-42ea-8d45-5af5f42b3d6b)

**Comment by Hector-Chong** [comment]
已经重新发布了 NPM 包。

> 这个文件在dist里面不存在，找不到类型 ![image](https://private-user-images.githubusercontent.com/37888349/369826727-1dc53992-7882-4846-adff-eecf6fa5457d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwOTU3NTYsIm5iZiI6MTcyNzA5NTQ1NiwicGF0aCI6Ii8zNzg4ODM0OS8zNjk4MjY3MjctMWRjNTM5OTItNzg4Mi00ODQ2LWFkZmYtZWVjZjZmYTU0NTdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDEyNDQxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjOWZmZWQwN2M5NTBmYjJiMDJjMjMwNDBhYWIwNDljMGFjN2RlZWYwMjc2ZGM1OTVkNjg3NWVmMGRhY2EyOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.e2Ub8UnpAMQGO0VopRbuPlG_bBd35tvZolgDmJ6Wvh0) ![image](https://private-user-images.githubusercontent.com/37888349/369826997-d126ccfc-618a-42ea-8d45-5af5f42b3d6b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwOTU3NTYsIm5iZiI6MTcyNzA5NTQ1NiwicGF0aCI6Ii8zNzg4ODM0OS8zNjk4MjY5OTctZDEyNmNjZmMtNjE4YS00MmVhLThkNDUtNWFmNWY0MmIzZDZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDEyNDQxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkN2I4YzAyZjE5YmI3MTAwNDQ0ZGJmMjIxYzllNGIwNzIxNTcwYjI1M2Q5ZmI0OTViZDIzODNlNzk1YThlYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Drvw7LvGQdcI_eSXSZA63t0UsONeXG5aZb01_58JIbk)

**Comment by hdjhdjhdj** [comment]
@Hector-Chong v1.0.18 更新完又找不到声明文件了
![image](https://github.com/user-attachments/assets/b9b5d3a8-5a90-4d58-9f6b-93d60b89d75f)

**Comment by Hector-Chong** [comment]
已重新发布 1.0.19。
