### ISSUE TITLE
分享的时候回来会跳转两次才完成分享， 然后还会占用剪贴板。

### ISSUE THREAD

**Issue by jameszhan02** [Hector-Chong/native-wechat#39]
https://github.com/little-snow-fox/react-native-wechat-lib/issues/118 
上面这个issue 里面有相关的universal link 配置问题。 然后配置完成后我还是有类似的问题， 不知道有没有上面解决方案？

**Comment by Hector-Chong** [comment]
可参考以下链接排查配置问题。

https://native-wechat.hector.im/guide/universal-link-checking.html

**Comment by jameszhan02** [comment]
解决了谢谢
