### ISSUE TITLE
麻烦问下有详细的文档吗

### ISSUE THREAD

**Issue by tangpostkarte** [Hector-Chong/native-wechat#40]
作者你好，麻烦有详细的文档吗，按着readme的操作好像有报错

TypeError: Cannot read property 'registerApp' of undefined

**Comment by tangpostkarte** [comment]
我找到文档了。https://native-wechat.hector.im 😄

**Comment by tangpostkarte** [comment]
我按着文档的配置方式配置了，不过还是报 (NOBRIDGE) ERROR  TypeError: Cannot read property 'registerApp' of undefined这个错误

**Comment by tangpostkarte** [comment]
![image](https://github.com/Hector-Chong/native-wechat/assets/48142567/32c3bee6-bfc9-49e2-9ae1-5f9c06934a9f)

**Comment by tangpostkarte** [comment]
感觉是和android版本有关https://stackoverflow.com/questions/77235063/one-of-receiver-exported-or-receiver-not-exported-should-be-specified-when-a-rec

**Comment by tangpostkarte** [comment]
我用的andorid14版本

**Comment by Hector-Chong** [comment]
Deplucate #38
