### ISSUE TITLE
有React Native 0.74版配置好的示例项目参考吗？

### ISSUE THREAD

**Issue by Wgga** [Hector-Chong/native-wechat#42]
作者大大，我是React Native新手小白一个，有React Native 0.74版配置好的示例项目，我这边安卓用的是Kotlin文件，IOS用的也是新架构，不知道配置的是否正确

**Comment by Hector-Chong** [comment]
谢谢提醒，我会在近期添加针对 Kotlin 的文档支持。Sent from my iPhoneOn Jun 29, 2024, at 21:50, GuaGua ***@***.***> wrote:﻿
作者大大，新手小白一个，有React Native 0.74版配置好的示例项目，我这边安卓用的是Kotlin文件，IOS用的也是新架构，不知道配置的是否正确

**Comment by Wgga** [comment]
> 谢谢提醒，我会在近期添加针对 Kotlin 的文档支持。从我的iPhone发送2024年6月29日21：50，瓜瓜***@***.***>写道： 作者大大，新手小白一个，有React Native 0.74版配置好的示例项目，我这边安卓用的是Kotlin文件，IOS用的也是新架构，不知道配置的是否正确 - 直接回复此电子邮件，在 GitHub 上查看或取消订阅。您收到此消息是因为您订阅了此线程。消息 ID：***@***.***>

嘿嘿，谢谢作者大大🥰

**Comment by yundGo** [comment]
同新人，希望有一份新版本的实例代码，辛苦☕️

**Comment by Hector-Chong** [comment]
文档已完成更新，Android 仍参照原配置，iOS 需额外变动。

https://native-wechat.hector.im/guide/configuration
