### ISSUE TITLE
在App.tsx中调用registerApp报错

### ISSUE THREAD

**Issue by Wgga** [Hector-Chong/native-wechat#43]
useEffect(()=>{
  registerApp({
    appid: "wx964290141ebe9b7b"
  });
}, [])
在App.tsx中调用registerApp报以下错误：
`new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.

**Comment by zhen-zhong** [comment]
没太理解，方便贴个代码么

**Comment by Wgga** [comment]
代码没有了，就是我在App.tsx中调用registerApp注册时，会报这个警告而已，应该时源码里registerApp方法里有关NativeEventEmitter这个的问题吧，具体我也不太清楚，只是警告而已，不算报错

**Comment by Yi-debug** [comment]
我也是报这个错误，有解决版本吗

**Comment by Wgga** [comment]
> 我也是报这个错误，有解决办法吗

没有跟进了，不知道作者解决没有

**Comment by Hector-Chong** [comment]
这个问题已经在最新版尝试修复过了，还是出现同样的提示吗？

**Comment by Yi-debug** [comment]
加上removeListeners就解决了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月14日(周四) 中午12:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Hector-Chong/native-wechat] 在App.tsx中调用registerApp报错 (Issue #43)




  
我也是报这个错误，有解决办法吗
  
没有跟进了，不知道作者解决没有

**Comment by Hector-Chong** [comment]
> > 这个问题已经在最新版尝试修复过了，还是出现同样的提示吗？
> 
> node_modules\native-wechat\android\src\oldarch\com\hector\nativewechat\NativeWechatModule.java node_modules\native-wechat\android\src\newarch\java\com\hector\nativewechat\NativeWechatModule.java
> 
> 在这两个文件下在加上 @ReactMethod public void removeListeners(String eventName) { } 这个代码就没问题了

方便给我提交一个 PR 吗？
