### ISSUE TITLE
使用RN0.74.3的版本 IOS集成不了

### ISSUE THREAD

**Issue by MR-ZiWeiter** [Hector-Chong/native-wechat#44]
使用RN0.74.3的版本集成时，按照文档说明添加所有的配置后，安装后的app依旧不可用，调用的方法直接返回error 为undefined。并且去查看NativeModules的WeChat是空的undefined.

安卓上面正常使用，无问题

**Comment by MR-ZiWeiter** [comment]
可以使用  没设置universalLink。但是安卓分享小程序报错
Exception in native call
com.facebook.react.bridge.NoSuchKeyException: miniProgramType

**Comment by sunnylqm** [comment]
https://github.com/Hector-Chong/native-wechat/blob/main/android/src/main/java/com/hector/nativewechat/NativeWechatModuleImpl.java#L292 
安卓端的大小写和js端的声明对不上

**Comment by Hector-Chong** [comment]
> https://github.com/Hector-Chong/native-wechat/blob/main/android/src/main/java/com/hector/nativewechat/NativeWechatModuleImpl.java#L292 安卓端的大小写和js端的声明对不上

https://github.com/Hector-Chong/native-wechat/commit/1a8d6098033a8bc3e2a84176235e0e138f49eb57
