### ISSUE TITLE
registerApp cannot rerun event listen

### ISSUE THREAD

**Issue by ryan-tsang** [Hector-Chong/native-wechat#46]
If registerApp is returned in useEffect, it will not rerun when enter to the same screen

``` 
useEffect(() => {
    const removeListener = registerApp({
      appid: Config.WECHAT_APP_ID,
      universalLink: Config.WECHAT_RETURN_URL,
    });
    return removeListener;
}, []);
```

[PR](https://github.com/Hector-Chong/native-wechat/pull/45) created

**Comment by Hector-Chong** [comment]
https://github.com/Hector-Chong/native-wechat/pull/45
