### ISSUE TITLE
Android调用后报警告new NativeEventEmitter()

### ISSUE THREAD

**Issue by Yi-debug** [Hector-Chong/native-wechat#53]
new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method

**Comment by Yi-debug** [comment]
`  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.23.1",
    "@react-native-camera-roll/camera-roll": "^7.7.0",
    "@react-native-community/datetimepicker": "^8.0.1",
    "@react-native-community/slider": "^4.5.2",
    "@react-navigation/bottom-tabs": "^6.5.20",
    "@react-navigation/native": "^6.1.17",
    "@react-navigation/native-stack": "^6.9.26",
    "@reduxjs/toolkit": "^2.2.3",
    "axios": "^1.6.8",
    "jcore-react-native": "^2.1.8",
    "jpush-react-native": "^3.0.8",
    "native-wechat": "^1.0.19",
    "patch-package": "^8.0.0",
    "react": "18.2.0",
    "react-native": "0.73.6",
    "react-native-blob-util": "^0.19.9",
    "react-native-collapsible": "^1.6.1",
    "react-native-contacts": "^7.0.8",
    "react-native-device-info": "^11.1.0",
    "react-native-document-picker": "^9.2.0",
    "react-native-exit-app": "^2.0.0",
    "react-native-fs": "^2.20.0",
    "react-native-image-picker": "^7.1.2",
    "react-native-image-zoom-viewer": "^3.0.1",
    "react-native-modalbox": "^2.0.2",
    "react-native-orientation-locker": "^1.7.0",
    "react-native-pager-view": "^6.3.1",
    "react-native-pdf": "^6.7.5",
    "react-native-pell-rich-editor": "^1.9.0",
    "react-native-permissions": "^4.1.5",
    "react-native-qrcode-svg": "^6.3.1",
    "react-native-render-html": "^6.3.4",
    "react-native-root-siblings": "^5.0.1",
    "react-native-safe-area-context": "^4.9.0",
    "react-native-screens": "^3.30.1",
    "react-native-share": "^10.2.1",
    "react-native-splash-screen": "^3.3.0",
    "react-native-step-indicator": "^1.0.3",
    "react-native-svg": "^15.3.0",
    "react-native-swipe-list-view": "^3.2.9",
    "react-native-swiper-flatlist": "^3.2.4",
    "react-native-tab-view": "^3.5.2",
    "react-native-vector-icons": "^10.0.3",
    "react-native-video": "^6.0.0",
    "react-native-webview": "^13.10.2",
    "react-redux": "^9.1.1",
    "redux-persist": "^6.0.0"
  },`

**Comment by Yi-debug** [comment]
"dependencies": {
    "@react-native-async-storage/async-storage": "^1.23.1",
    "@react-native-camera-roll/camera-roll": "^7.7.0",
    "@react-native-community/datetimepicker": "^8.0.1",
    "@react-native-community/slider": "^4.5.2",
    "@react-navigation/bottom-tabs": "^6.5.20",
    "@react-navigation/native": "^6.1.17",
    "@react-navigation/native-stack": "^6.9.26",
    "@reduxjs/toolkit": "^2.2.3",
    "axios": "^1.6.8",
    "jcore-react-native": "^2.1.8",
    "jpush-react-native": "^3.0.8",
    "native-wechat": "^1.0.19",
    "patch-package": "^8.0.0",
    "react": "18.2.0",
    "react-native": "0.73.6",
    "react-native-blob-util": "^0.19.9",
    "react-native-collapsible": "^1.6.1",
    "react-native-contacts": "^7.0.8",
    "react-native-device-info": "^11.1.0",
    "react-native-document-picker": "^9.2.0",
    "react-native-exit-app": "^2.0.0",
    "react-native-fs": "^2.20.0",
    "react-native-image-picker": "^7.1.2",
    "react-native-image-zoom-viewer": "^3.0.1",
    "react-native-modalbox": "^2.0.2",
    "react-native-orientation-locker": "^1.7.0",
    "react-native-pager-view": "^6.3.1",
    "react-native-pdf": "^6.7.5",
    "react-native-pell-rich-editor": "^1.9.0",
    "react-native-permissions": "^4.1.5",
    "react-native-qrcode-svg": "^6.3.1",
    "react-native-render-html": "^6.3.4",
    "react-native-root-siblings": "^5.0.1",
    "react-native-safe-area-context": "^4.9.0",
    "react-native-screens": "^3.30.1",
    "react-native-share": "^10.2.1",
    "react-native-splash-screen": "^3.3.0",
    "react-native-step-indicator": "^1.0.3",
    "react-native-svg": "^15.3.0",
    "react-native-swipe-list-view": "^3.2.9",
    "react-native-swiper-flatlist": "^3.2.4",
    "react-native-tab-view": "^3.5.2",
    "react-native-vector-icons": "^10.0.3",
    "react-native-video": "^6.0.0",
    "react-native-webview": "^13.10.2",
    "react-redux": "^9.1.1",
    "redux-persist": "^6.0.0"
  },

**Comment by Asad520** [comment]
I get the same warning when I call registerApp({...appConfig}). Did you find a solution to this?
