### ISSUE TITLE
请问下大佬，安装这个库之后ios无法启动，有如下报错

### ISSUE THREAD

**Issue by kaeldxy** [Hector-Chong/native-wechat#9]
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_RCTBridge", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_RCTBundleURLProvider", referenced from:
      objc-class-ref in AppDelegate.o
  "_RCTAppSetupDefaultRootView", referenced from:
      -[AppDelegate application:didFinishLaunchingWithOptions:] in AppDelegate.o
  "_RCTAppSetupPrepareApp", referenced from:
      -[AppDelegate application:didFinishLaunchingWithOptions:] in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by kaeldxy** [comment]
> 

我的mac是M1芯片的，跟这个有关系吗

**Comment by Hector-Chong** [comment]
这似乎和你的电脑是有关系的，因为使用了和 ARM 架构（M1）不同的 x86 implement 编译 C++ 代码。

如果方便的话，请如下图所示，提供对应 Target 的 Architecture 部分截图，或在 Build Settings 里搜索 x86 相关字样。

<img width="928" alt="image" src="https://user-images.githubusercontent.com/12469549/205815105-8bc18619-d7de-47b4-8777-283a35e3120c.png">

**Comment by kaeldxy** [comment]
![image](https://user-images.githubusercontent.com/62943052/205827474-cb8d947d-3868-4859-abc2-60d280aef466.png)
大佬请看，我之前尝试过修改这些值，但不起作用，我之前也在网上看到有人说可能是有的静态库不支持编译到模拟器，但不知道怎么去修改

**Comment by kaeldxy** [comment]
![image](https://user-images.githubusercontent.com/62943052/205833713-a25fcc34-36c9-4984-bcc9-0ce711cef040.png)
这是搜索 x86 的结果

**Comment by Hector-Chong** [comment]
你可尝试将 `i386` 修改为 `arm64`。

<img width="470" alt="image" src="https://user-images.githubusercontent.com/12469549/205843171-3aec0950-bac2-4c8b-a166-57008455a470.png">

另外亦可尝试将 `C++ Language Dialect` 设置为 `C++17`。

<img width="441" alt="image" src="https://user-images.githubusercontent.com/12469549/205843567-e0836800-fab8-4b81-87e3-99457aaf378a.png">

**Comment by kaeldxy** [comment]
好的，感谢大佬，🙏
